### PR TITLE
Harker blog

### PR DESCRIPTION
**Pull request by rlh100**
Three blog postings.  I know they are meeting summaries but that is what I am writing.  So for now they should be blog entries since the web site has a page for blogs.  Once we get some more traditional blog posts we can move them off the blog page.

Can we list the posts in reverse cronological order.  Newest first, oldest last?

Is this a workable plan?

### CODE REVIEW

**Comment by rlh100** [comment]
What does the error:
All checks have failed
mean?

Is this because the blogs page is not defined?

Where is the configuration information/settings for Travis kept?
Thx
RLH

**Comment by verythorough** [comment]
Sorry for the delay.  Travis config is in the `.travis.yml` file at the repo root.  The build is failing because jekyll takes a `yyyy-mm-dd-title.md` filename and assigns the url http://opensmc.org/blog/title, which causes a conflict when processing `2016-04-19-hacknight.md` and `2016-04-26-hacknight.md`

Regarding posts and organization, I'm going to reformat the Events page a bit to feature upcoming meetups as well as your notes and any speaker materials from past ones.  I will probably also propose some changes for the front page to include this dynamic content as well.

**Comment by rlh100** [comment]
Thats stupid.  Why doesn't .2016-04-26-hacknight.md translate to 2016-04-26-hacknight.html which is what I expected.
Will 2016-04-26-hacknight-2016-04-26.md work?
The human can work around the defects of the computer.

**Comment by verythorough** [comment]
I don't think it's necessary to resort to name-calling.  Our jekyll post-naming structure is set to take a format useful to the writer (easily sort a folder of post files by date, etc.) and translate it to the standard link format that users are accustomed to, i.e., "example.com/this-is-the-title".

Your workaround will work, but ideally, the filename should reflect the actual human-readable post title, for example, `2016-04-26-opensmc-hacknight-steady-progress-on-projects.md` or possibly shortened to `2016-04-26-steady-progress-on-projects.md`.

**Comment by verythorough** [comment]
As we transition to making these meeting notes their own type of post, I wonder if it will make more sense to title them according to how many hacknights we've had, for example, `2016-04-26-hacknight-17.md`, and "Hacknight #.17: Possible Subtitle".  (The dot in the title is to prevent gtihub from linking this comment to Issue #17.)  I like the idea of tallying our hacknights!

**Comment by rlh100** [comment]
I have a strong dislike of 30 character file names.  I do most of my work on an 80 character wide terminal screen.
My background as a sysadmin makes me prefer dates over sequence numbers.  But that is just a personal preference.
Lets go with sequence numbers.

I think I have a couple of meeting summaries from January.  Should I include those?

**Comment by verythorough** [comment]
Yes, it does make for ridiculously long filenames.  As for dates vs. sequence numbers, we do still have the date information, both in the beginning of the filename, and in the post date field.

I think it would be great to have your January meeting summaries as well.

**Comment by rlh100** [comment]
Filename changes and new content has been added

**Pull request closed without merging**
